version: '3.6'
services:
  opcpublisher:
    command: publisher --pf=/appdata/pn.json --aa
    container_name: opcpublisher
    environment:
    - EdgeHubConnectionString=<connection string>
    expose:
    - 62222/tcp
    hostname: publisher
    image: mcr.microsoft.com/iotedge/opc-publisher:latest
    ports:
    - 62222:62222/tcp
    restart: always
    volumes:
    - /tmp/opcpub:/appdata
volumes:
  edgemoduledev:
    name: edgemoduledev
